with-expecter: True
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "Mock{{firstUpper .InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{lower .InterfaceName}}.go"
all: True
packages:
  github.com/blcvn/corev4-explorer/usecases:
    config:
      recursive: True