package oracle

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/blcvn/corev4-explorer/appconfig"
	"github.com/blcvn/corev4-explorer/types"
	"github.com/godror/godror"
)

const (
	sql_INIT_TABLE_TASK = `CREATE TABLE %s (
		"ID" NUMBER GENERATED by default on null as IDENTITY,
		"TYPE" NUMBER,
		"STATUS" NUMBER,
		"BLOCK_NUM" NUMBER,
		"NETWORK_NAME" VARCHAR(255),
		"CHANNEL_NAME" VARCHAR(255),
		"CREATE_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)`
	sql_INSERT_TASK = `INSERT INTO %s (TYPE, STATUS, BLOCK_NUM, NETWORK_NAME, CHANNEL_NAME)
	VALUES(:1, :2, :3, :4, :5)`
)

func (odb *OracleDB) InitTableTask(ctx context.Context) error {
	tableName := appconfig.OnchainTableNameMapping["task"]

	sql1 := fmt.Sprintf(SQL_CHECK_TABLE_EXISTED, tableName)
	result, err := odb.Client.QueryContext(ctx, sql1, godror.FetchArraySize(1))
	if err != nil {
		return err
	}

	defer result.Close()

	var existed int
	for result.Next() {
		if err := result.Scan(&existed); err == nil {
			err := fmt.Errorf("table %s existed", tableName)
			odb.logger.Warn(err)
			return err
		}
	}

	sql2 := fmt.Sprintf(sql_INIT_TABLE_TASK, tableName)
	_, err = odb.Client.ExecContext(ctx, sql2)
	if err != nil {
		odb.logger.Errorf("Failed to create table %s : %v", tableName, err)
		return err
	}

	odb.logger.Infof("table %s is created successfully", tableName)

	return nil
}

func (odb *OracleDB) InsertTask(ctx context.Context, dbTransaction *sql.Tx, task *types.TaskOracle) error {

	// Prepare the SQL statement
	tableName := fmt.Sprintf("%s.%s", odb.Schema, appconfig.OnchainTableNameMapping["task"])
	sql := fmt.Sprintf(sql_INSERT_TASK, tableName)

	if dbTransaction != nil {
		_, err := dbTransaction.ExecContext(ctx, sql,
			task.Type,
			task.Status,
			task.BlockNumber,
			task.NetworkName,
			task.ChannelName,
		)

		if err != nil {
			return err
		}
	} else {
		_, err := odb.Client.ExecContext(ctx,
			sql,
			task.Type,
			task.Status,
			task.BlockNumber,
			task.NetworkName,
			task.ChannelName,
		)

		if err != nil {
			return err
		}

	}
	return nil
}
